spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    username: root
    password: 241198
    url: jdbc:mysql://localhost:3306/crud?useTimezone=true&serverTimezone=UTC

service:
  name: "crud"